host = "localhost"
port = 5432
user = "musicadmin"
password = "gsds2023#"
dbname = "promptdb"
# upload_folder = "/home/duclv/project/openai/web_backend/uploads"
upload_folder = "./uploads"
# allowed_extensions = {'csv'}
allowed_extensions = {}
open_api_mode = False